name: Build and Deploy LaTeX Documents for matrix_algebra_learning_notes

on:
  push:
    paths:
      - 'math/matrix_algebra/matrix_algebra_learning_notes/**.tex'
      - '.github/workflows/matrix_algebra_learning_notes.yml'
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  MAIN_FILE: matrix_algebra_learning_notes
  OUTPUT_DIR: math/matrix_algebra/matrix_algebra_learning_notes/build
  SOURCE_DIR: math/matrix_algebra/matrix_algebra_learning_notes

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      # Modified to support multiple compilation passes
      - name: Compile LaTeX document
        working-directory: ${{ env.SOURCE_DIR }}
        run: |
          # First pass - generates aux files
          xelatex -interaction=nonstopmode ${{ env.MAIN_FILE }}
          # Generate bibliography if you have citations
          if [ -f "${{ env.MAIN_FILE }}.bib" ]; then
            bibtex ${{ env.MAIN_FILE }}
          fi
          # Second pass - generates TOC
          xelatex -interaction=nonstopmode ${{ env.MAIN_FILE }}
          # Final pass - ensures all references are correct
          xelatex -interaction=nonstopmode ${{ env.MAIN_FILE }}

      - name: Create output directory
        run: |
          mkdir -p ${{ env.OUTPUT_DIR }}
          cp ${{ env.SOURCE_DIR }}/${{ env.MAIN_FILE }}.pdf ${{ env.OUTPUT_DIR }}/

      - name: Verify PDF generation
        run: |
          if [ ! -f "${{ env.OUTPUT_DIR }}/${{ env.MAIN_FILE }}.pdf" ]; then
            echo "matrix_algebra_learning_notes PDF file was not generated successfully!"
            exit 1
          fi
          echo "matrix_algebra_learning_notes PDF file was generated successfully!"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: ${{ env.OUTPUT_DIR }}/${{ env.MAIN_FILE }}.pdf
          if-no-files-found: error

      - name: Configure Git
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and push PDF
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          while [ -f /tmp/git-lock ];
            do sleep 1;
          done

          touch /tmp/git-lock

          git pull origin main

          git add ${{ env.OUTPUT_DIR }}/${{ env.MAIN_FILE }}.pdf

          git commit -m "Update matrix_algebra_learning_notes PDF documentation with TOC" || echo "No changes to commit"

          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}

          rm /tmp/git-lock

      - name: Create issue on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '❌ matrix_algebra_learning_notes LaTeX Compilation Failed',
              body: `Failed commit: ${context.sha}\nPlease check the logs for details.`
            })